#!/bin/bash

# Helper script to run Deptrac
# Usage: ./deptrac [args]
# Examples:
#   ./deptrac analyze
#   ./deptrac analyze --report-uncovered

cd "$(dirname "$0")"

docker-compose exec php vendor/bin/deptrac "$@"
